### ISSUE TITLE
autojump to anchor

### ISSUE THREAD

**Issue by am35a** [ayndqy/svelte-micro#19]
Is it possible to make an automatic anchor jump(scroll to anchor) when following a link or any route?

https://github.com/am35a/S4/blob/rename-utilities/app/src/lib/layout/authorized/main/utilities/Utilities.svelte#L36C27-L36C87

<img width="554" alt="image" src="https://github.com/ayndqy/svelte-micro/assets/17111965/7640ade2-5688-4549-b96b-74a2cdd90c54">

tnx

**Comment by ayndqy** [comment]
Hi @am35a,
Due to the nature of SPA routing, all route content is mounted dynamically, which prevents the browser from automatically jumping to the element with the id specified in the hash.

However, it's possible to implement this behaviour using this svelte action:
```javascript
const anchorJump = (node, { hash }) => {
  let observer;

  const observe = (id) => {
    if (observer) observer.disconnect();

    const element = document.getElementById(id);

    if (element !== null) {
      element.scrollIntoView();
      return;
    }

    observer = new MutationObserver(() => {
      const element = document.getElementById(id);
      if (element !== null) {
        element.scrollIntoView();
        observer.disconnect();
      }
    });

    observer.observe(node, { childList: true, subtree: true });
  };

  const unsubscribe = hash.subscribe((value) => {
    const id = value.slice(1);
    if (id !== "") observe(id);
  });

  return {
    destroy() {
      unsubscribe();
      if (observer) observer.disconnect();
    },
  };
};
```

Whenever the value of the hash store changes, it will track dom mutations using the MutationObserver API, and if an element with the required id is found, it will scroll to that element and detach the observer.

You can apply this action on the `<svelte:body />` special element in your App.svelte file to apply this behaviour on every element on the page:
```svelte
<script>
  import { hash } from "svelte-micro";
</script>

<svelte:body use:anchorJump={{ hash }} />
```

**Comment by ayndqy** [comment]
Just updated the example, now the action can scroll to the element even if the DOM tree is not updated, but the element exists.

**Comment by am35a** [comment]
thank you so much!
