### ISSUE TITLE
Dynamic routes?

### ISSUE THREAD

**Issue by howesteve** [ayndqy/svelte-micro#6]
Sorry for opening an issue for a doubt. But what's the suggested way to handle dynamic routes? Sort of what other routers do with ```/xxx/*``` routes.
```GET /messsages/xxxxxxxxx```
I have to get the ```xxxxxxxxx``` part of the url.

Do I have to watch and parse ```$path``` manually?

EDIT: I'm currently using a ```{#if}``` block inspecting ```$path```.

Thanks

**Comment by ayndqy** [comment]
In svelte-micro there is different approach to pass dynamic data inside routes called $query.
In this case the URL would look like this: "/message?id=xxxxxx".

To reactively get `id` param you can use similar construction: 
```svelte
<script>
  $: id = new URLSearchParams($query).get("id") ?? "fallback";
</script>
```

More related information: https://github.com/ayndqy/svelte-micro#stores-usage

**Comment by howesteve** [comment]
Thanks for the answer. Actually it's not a query param in my case, but instead a part of the query path:

```GET /messsages/xxxxxxxxx```

However I'm using a similar approach which seems to be working fine:
``` svelte
<script>
let msgId = '';
$: {
  const res = /^\/messages\/([0-9a-fA-F\-]+)/i.exec($path);
  msgId = res ? res[1] : '';
}
</script>
```
That could be a nice example to add to docs, if you want.

**Comment by ayndqy** [comment]
In my opinion it's not a good practice to store dynamic data inside pathname, because when `$path` changes, every value inside the route tree should be recomputed. For this purpose there is `$hash` and `$query`, which are not used by Route component. Also the advantage of `$query` is that you can pass multiple dynamic parameters.

But keep in mind that the props of `<Route />` component is reactive, so maybe that property can be useful in your case.

Sorry for the not very appropriate answer, but I recommend you use the `$query` store and `/message?property=xxxxxx` instead of parsing it from `$path` due to better performance of the first approach.

**Comment by howesteve** [comment]
I actually agree with you, but I cannot change the server api. This kind of api path routing is largely used in all REST architectures, it's "kinda" a industry standard...

**Comment by ayndqy** [comment]
svelte-micro is client-side router and it was not designed to be used on a server. You still can use path-only routing on server.

**Comment by howesteve** [comment]
Yes, I only use svelte-micro on the client as designed. But I'm accessing a thirdy party's server api I don't have any control of, so I must stick to it's designed api/urls...

**Comment by ayndqy** [comment]
Actually, client routes and server API routes do not necessarily have to match, so I don't see a problem here.

**Comment by Enes5519** [comment]
Too bad it doesn't have a dynamic routing structure, I guess I'll have to find another library.
